### PR TITLE
fix: Adding tags to the CSExtension and BillingExtension

### LINKED ISSUE #784: How to add Tags to created underlying resources via Karpenter.
### Is an existing page relevant?

Version 0.7.0

### What karpenter features are relevant?

Hi Team,
I am trying out the Karpenter Self Hosted Version. 

In my Azure Account, I have mandatory tags policies which needs to be applied to any new resources created.
However when karpenter is trying to spawn up new nodes, I get an error of Tags not being applied to nodes at the time of creation?

Can someone help me out how this can be achieved? In nodeclass or Nodepool or somewhere else?

Thanks.

Your support will be highly appreciated.

### How should the docs be improved?

Let me know how can we add tags at the time of resource creation done by Karpenter?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by aagusuab**
Fixes #784 

**Description**
Previously, the tag changes from AKSNodeClass was not applied to the CSExtension's tags. 
This PR adds those tags to the CSExtensions' tags.

**How was this change tested?**

* Test Added to check CSExtension's tags drifted from the AKSNodeClass

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```NONE

```

### CODE REVIEW

File: test/suites/drift/suite_test.go [hunk 1]
```diff
@@ -740,4 +741,26 @@ var _ = Describe("Drift", func() {
 		By(fmt.Sprintf("waiting for nodeclaim %s to be marked as drifted", nodeClaim.Name))
 		env.EventuallyExpectDrifted(nodeClaim)
 	})
+
+	It("should apply tags to CSE extension", func() {
```
Comment (Bryce-Soghigian) [inline test/suites/drift/suite_test.go:745]: Change the options, to use ProvisionMode == bootstrapping client. 


We should be able to override the test options to accept bootstrapping client as a parameter.

Comment (tallaxes) [reply test/suites/drift/suite_test.go]: As @Bryce-Soghigian have discovered earlier, overriding options would not work in the current testing framework unless you re-create the testing Environment from the new options.

File: pkg/providers/instance/suite_test.go [hunk 2]
```diff
@@ -291,4 +293,90 @@ var _ = Describe("InstanceProvider", func() {
...
+		It("should create Windows CSExtension with correct configuration", func() {
+			nodeClass.Spec.ImageFamily = lo.ToPtr("Windows2019")
+			ExpectApplied(ctx, env.Client, nodePool, nodeClass)
+
+			pod := coretest.UnschedulablePod(coretest.PodOptions{})
+			ExpectProvisioned(ctx, env.Client, cluster, cloudProvider, coreProvisioner, pod)
+			ExpectScheduled(ctx, env.Client, pod)
+
+			Expect(azureEnv.VirtualMachinesAPI.VirtualMachineCreateOrUpdateBehavior.CalledWithInput.Len()).To(Equal(1))
+
```
Comment (Bryce-Soghigian) [inline pkg/providers/instance/suite_test.go]: We don't support windows, this was some feedback I had on the 2a code that it may make things confusing to put all the wiring. 

 [FAILED] Expected success, but got an error:
      <*errors.StatusError | 0xc000dfe140>: 
      AKSNodeClass.karpenter.azure.com "roarerclever-51-7wy0bfzllv" is invalid: [spec.imageFamily: Unsupported value: "Windows2019": supported values: "Ubuntu2204", "AzureLinux", <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
      
      Wont work with windows.

File: pkg/providers/instance/suite_test.go [hunk 3]
```diff
@@ -291,4 +293,44 @@ var _ = Describe("InstanceProvider", func() {
...
 	})
+	Context("CSExtension", func() {
+		var originalOptions *options.Options
+
+		BeforeEach(func() {
+			originalOptions = options.FromContext(ctx)
+			ctx = options.ToContext(
+				ctx,
+				test.Options(test.OptionsFields{
+					ProvisionMode: lo.ToPtr(consts.ProvisionModeBootstrappingClient),
```
Comment (Bryce-Soghigian) [inline pkg/providers/instance/suite_test.go:304]: since ProvisionMode is passed as a parameter to the InstanceProvider, we need to also recreate the azureEnv. 

This wont execute with CSE Extension, and when you get there I suspect you will run into an error about node bootstrapping URL not being able to find the host, since we dont implement a fake for it

File: test/suites/drift/suite_test.go (hunk 1 above)
Comment (tallaxes) [reply test/suites/drift/suite_test.go]: ... and therefore what Bryce was suggesting won't work without extra effort to shape fakes correctly. I would not expect @aagusuab to do that work in this PR. Until this is in place, we may have to rely on manual testing and maybe E2E test in environment that uses bootstrap client. (The E2E test can be written to depend on that, I think).

Comment (Bryce-Soghigian) [reply test/suites/drift/suite_test.go]:
```
~/dev/focus/karpenter-provider-azure/pkg/providers/instance (aagusuab/cse_tags*) » git --no-pager diff                                                                                                                               sillygoose@mac
diff --git a/pkg/providers/instance/suite_test.go b/pkg/providers/instance/suite_test.go
index c2c3cbc..55802db 100644
--- a/pkg/providers/instance/suite_test.go
+++ b/pkg/providers/instance/suite_test.go
@@ -293,7 +293,7 @@ var _ = Describe("InstanceProvider", func() {
                Expect(len(interfaces)).To(Equal(1))
                Expect(interfaces[0].Name).To(Equal(managedNic.Name))
        })
-       Context("CSExtension", func() {
+       FContext("CSExtension", func() {
                var originalOptions *options.Options

                BeforeEach(func() {
@@ -303,6 +303,8 @@ var _ = Describe("InstanceProvider", func() {
                                test.Options(test.OptionsFields{
                                        ProvisionMode: lo.ToPtr(consts.ProvisionModeBootstrappingClient),
                                }))
+                       azureEnv = test.NewEnvironment(ctx, env)
+                       cloudProvider = cloudprovider.New(azureEnv.InstanceTypesProvider, azureEnv.InstanceProvider, events.NewRecorder(&record.FakeRecorder{}), env.Client, azureEnv.ImageProvider)
                })

                AfterEach(func() {
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
~/dev/focus/karpenter-provider-azure/pkg/providers/instance (aagusuab/cse_tags*) » go test                                                                                                                                           sillygoose@mac
Running Suite: Provider/Azure - /Users/sillygoose/dev/focus/karpenter-provider-azure/pkg/providers/instance
===========================================================================================================
Random Seed: 1746495083

Will run 1 of 9 specs
SSSSSSSS{"time":"2025-05-05T18:31:28.525431-07:00","level":"ERROR","msg":"finished call","source":"ApiRequestLog","protocol":"REST","method_type":"unary","component":"client","time_ms":0,"method":"GET nodebootstrapping - LIST","service":"","url":"http:///subscriptions/12345678-1234-1234-1234-123456789012/resourceGroups/test-cluster-resource-group/providers/Microsoft.ContainerService/managedclusters/test-cluster/nodeBootstrapping","headers":null,"error":"http: no Host in request URL","code":"na"}

------------------------------
• [FAILED] [2.063 seconds]
InstanceProvider CSExtension [It] should create CSExtension with correct configuration
/Users/sillygoose/dev/focus/karpenter-provider-azure/pkg/providers/instance/suite_test.go:314

  [FAILED] expected default/pipercrazy-6-u2mpiinjen to be scheduled
  Expected
      <string>:
  not to be empty
  In [It] at: /Users/sillygoose/dev/focus/karpenter-provider-azure/pkg/providers/instance/suite_test.go:318 @ 05/05/25 18:31:28.526
------------------------------

Summarizing 1 Failure:
  [FAIL] InstanceProvider CSExtension [It] should create CSExtension with correct configuration
  /Users/sillygoose/dev/focus/karpenter-provider-azure/pkg/providers/instance/suite_test.go:318
  ```

Comment (Bryce-Soghigian) [reply test/suites/drift/suite_test.go]: I simply added a new azureEnv + cloudProvider which will run instance provider with the new options, you can see it fails with 

```
"GET nodebootstrapping - LIST","service":"","url":"http:///subscriptions/12345678-1234-1234-1234-123456789012/resourceGroups/test-cluster-resource-group/providers/Microsoft.ContainerService/managedclusters/test-cluster/nodeBootstrapping","headers":null,"error":"http: no Host in request URL","code":"na"}
```

File: pkg/providers/instance/suite_test.go (hunk 2 above)
Comment (aagusuab) [reply pkg/providers/instance/suite_test.go]: Deleted the Windows related test.

File: pkg/providers/instance/instance.go [hunk 4]
```diff
@@ -893,6 +893,7 @@ func (p *DefaultProvider) getCSExtension(cse string, isWindows bool) *armcompute
 				"commandToExecute": cse,
 			},
 		},
+		Tags: tags,
```
Comment (Bryce-Soghigian) [inline pkg/providers/instance/instance.go:896]: We should also add tags to the AKSIdentifyingExtension if we don't already.

File: test/suites/drift/suite_test.go (hunk 1 above)
Comment (aagusuab) [reply test/suites/drift/suite_test.go]: Changed the provisionMode to be bootstrapping client.

File: pkg/providers/instance/instance.go (hunk 4 above)
Comment (aagusuab) [reply pkg/providers/instance/instance.go:897]: Added the tags to the AKSIdentifyingExtension.

File: pkg/providers/instance/suite_test.go (hunk 3 above)
Comment (aagusuab) [reply pkg/providers/instance/suite_test.go]: Removed tests overall, per discussion with Alex

**Comment by Bryce-Soghigian** [comment]
https://github.com/Azure/karpenter-provider-azure/issues/784#issuecomment-2792253293 customer said the billing extension is also missing the tags. 

Should we add them for both CSE + Billing?

**Comment by aagusuab** [comment]
Will add another PR for E2E testing CSExtension related things, here is an example of CSExtension with tags:
```
 "resourceGroup": "MC_YOUNJAEEBLD123636494_TESTCLUSTER_EASTUS2",
    "resources": [
      {
        "autoUpgradeMinorVersion": null,
        "enableAutomaticUpgrade": null,
        "forceUpdateTag": null,
        "id": "/subscriptions/18153b17-4e27-4b58-863e-f8105b8892a2/resourceGroups/MC_YOUNJAEEBLD123636494_TESTCLUSTER_EASTUS2/providers/Microsoft.Compute/virtualMachines/aks-general-purpose-dxrg2/extensions/computeAksLinuxBilling",
        "instanceView": null,
        "location": null,
        "name": null,
        "protectedSettings": null,
        "protectedSettingsFromKeyVault": null,
        "provisionAfterExtensions": null,
        "provisioningState": null,
        "publisher": null,
        "resourceGroup": "MC_YOUNJAEEBLD123636494_TESTCLUSTER_EASTUS2",
        "settings": null,
        "suppressFailures": null,
        "tags": null,
        "type": null,
        "typeHandlerVersion": null,
        "typePropertiesType": null
      },
      {
        "autoUpgradeMinorVersion": null,
        "enableAutomaticUpgrade": null,
        "forceUpdateTag": null,
        "id": "/subscriptions/18153b17-4e27-4b58-863e-f8105b8892a2/resourceGroups/MC_YOUNJAEEBLD123636494_TESTCLUSTER_EASTUS2/providers/Microsoft.Compute/virtualMachines/aks-general-purpose-dxrg2/extensions/cse-agent-karpenter",
        "instanceView": null,
        "location": null,
        "name": null,
        "protectedSettings": null,
        "protectedSettingsFromKeyVault": null,
        "provisionAfterExtensions": null,
        "provisioningState": null,
        "publisher": null,
        "resourceGroup": "MC_YOUNJAEEBLD123636494_TESTCLUSTER_EASTUS2",
        "settings": null,
        "suppressFailures": null,
        "tags": null,
        "type": null,
        "typeHandlerVersion": null,
        "typePropertiesType": null
      }
    ],
    "scheduledEventsPolicy": null,
    "scheduledEventsProfile": null,
    "securityProfile": null,
    "storageProfile": {
      "dataDisks": [],
      "diskControllerType": "SCSI",
      "imageReference": {
        "communityGalleryImageId": "/CommunityGalleries/AKSUbuntu-38d80f77-467a-481f-a8d4-09b6d4220bd2/images/2204gen2containerd/versions/202505.06.0",
        "exactVersion": "202505.06.0",
        "id": null,
        "offer": null,
        "publisher": null,
        "sharedGalleryImageId": null,
        "sku": null,
        "version": null
      },
      "osDisk": {
        "caching": "None",
        "createOption": "FromImage",
        "deleteOption": "Delete",
        "diffDiskSettings": null,
        "diskSizeGb": 128,
        "encryptionSettings": null,
        "image": null,
        "managedDisk": {
          "diskEncryptionSet": null,
          "id": "/subscriptions/18153b17-4e27-4b58-863e-f8105b8892a2/resourceGroups/MC_younjaeebld123636494_testcluster_eastus2/providers/Microsoft.Compute/disks/aks-general-purpose-dxrg2",
          "resourceGroup": "MC_younjaeebld123636494_testcluster_eastus2",
          "securityProfile": null,
          "storageAccountType": "Premium_LRS"
        },
        "name": "aks-general-purpose-dxrg2",
        "osType": "Linux",
        "vhd": null,
        "writeAcceleratorEnabled": null
      }
    },
    "tags": {
      "environment": "test",
      "karpenter.azure.com_cluster": "testcluster",
      "karpenter.sh_nodepool": "general-purpose",
      "purpose": "scaling-test",
      "test-tag-1": "test-value-1",
      "test-tag-2": "test-value-2"
    },
    "timeCreated": "2025-05-08T21:57:26.091298+00:00",
    "type": "Microsoft.Compute/virtualMachines",
    "userData": null,
    "virtualMachineScaleSet": null,
    "vmId": "5af1bc5f-8cd6-49b2-9eaf-6018053db017",
    "zones": [
      "1"
    ]
  }
]
```

**Review by Bryce-Soghigian — APPROVED** [review]
LGTM, followup with an e2e test that checks tags, i can help here as well.
