### PR TITLE
fix: use zone "0" for regional VMs to match AKS node labels

### LINKED ISSUE #1384: Topology spread constraints fail with empty zone domain in counts
### Version

Karpenter version: 1.6.6, and 1.7.1
Mode: Self hosted (see below comment, someone reproduced with NAP as well).
Kubernetes version: 1.33
Region: eastus2

### Expected Behavior

With topology spread constraint `maxSkew: 1` and `whenUnsatisfiable: DoNotSchedule`, Karpenter should provision nodes in zones that satisfy the constraint.

**Current distribution:** `zone1=2, zone2=1, zone3=1`
**Expected:** Provision in zone2 or zone3 (maxSkew would be 1)

### Actual Behavior

Karpenter reports topology constraint as unsatisfiable and refuses to provision nodes. Logs show an unexpected empty string domain in topology counts:

```
counts = : 0, eastus2-1: 2, eastus2-2: 1, eastus2-3: 1
```

This appears to cause incorrect maxSkew calculation. My guess here is that the first part of that error string is missing a zone, hence ` : 0`, when others have format `$zone: $count`.

### Steps to Reproduce the Problem

1. Deploy with topology spread constraints in a zonal region:

```yaml
topologySpreadConstraints:
  - maxSkew: 1
    topologyKey: topology.kubernetes.io/zone
    whenUnsatisfiable: DoNotSchedule
    labelSelector:
      matchLabels:
        app.kubernetes.io/name: my-name
```

2. Scale to create pending pods requiring new nodes

3. Observe Karpenter refusing to provision despite valid zones available

### Resource Specs and Logs

Note, we have two node pools, `default` and `ephemeral` (spot instances for cronjob job pods).

In both cases for us, one Deployment, and one Statefulset, both using the `default` nodepool, caused this error.

```json
{"level":"ERROR","time":"2026-01-27T18:23:45.982Z","logger":"controller","message":"could not schedule pod","commit":"28204ca","controller":"provisioner","namespace":"","name":"","reconcileID":"7b152da1-16b0-41a1-a483-025bfe3f72ca","Pod":{"name":"<REDACTED_POD_NAME>","namespace":"<REDACTED_POD_NAMESPACE>"},"taint":"dedicated=ephemeral:NoSchedule","error":"did not tolerate taint (taint=dedicated=ephemeral:NoSchedule); unsatisfiable topology constraint for topology spread, key=topology.kubernetes.io/zone (counts = : 0, eastus2-1: 1, eastus2-2: 1, eastus2-3: 1, podDomains = topology.kubernetes.io/zone Exists, nodeDomains = topology.kubernetes.io/zone Exists","errorCauses":[{"error":"did not tolerate taint (taint=dedicated=ephemeral:NoSchedule)"},{"error":"unsatisfiable topology constraint for topology spread, key=topology.kubernetes.io/zone (counts = : 0, eastus2-1: 1, eastus2-2: 1, eastus2-3: 1, podDomains = topology.kubernetes.io/zone Exists, nodeDomains = topology.kubernetes.io/zone Exists"}]}
```

### Short-term mitigation

Switching from `DoNotSchedule` to `ScheduleAnyway` allowed Karpenter to create a node, and immediately following, saw the event `Pod should schedule on: nodeclaim/$name`.

I include this because it seems to me that this setting is only really for the kube scheduler, and since karpenter _still_ needed to create a new node to fit, it probably should have been able to do so in the earlier case with `DoNotSchedule`. In fact, we rely on `DoNotSchedule` to require karpenter to schedule a new node in another zone, so that we maintain zone spread.

This is what leads me to believe this is a bug in the implementation somewhere.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by tallaxes**
Fixes https://github.com/Azure/karpenter-provider-azure/issues/1384

**Description**

Regional (non-zonal) VM SKUs were internally represented with `topology.kubernetes.io/zone=""` (empty string). The empty string caused two problems. 
* First, it was inserted into topology-spread domain counts as a zero-count domain, which could poison maxSkew calculations even when users never explicitly targeted it. 
* Second, Karpenter core also uses "" as the internal sentinel for "no valid domain selected" in nextDomainTopologySpread, so if the scheduler ever did select the empty domain as the best candidate, it converted that selection into DoesNotExist and treated scheduling as unsatisfiable.

Switching regional VM zones to "0" fixes the sentinel collision and matches AKS's regional node label, but it does not by itself fix every case where an extra regional domain participates in topology-spread skew math.

Key changes:
- Add `RegionalZone` constant (`"0"`) for the regional VM zone label value
- Add `MakeAKSLabelZoneFromARMZones()` that takes an ARM zones array directly, eliminating intermediate empty-string zone values
- Update all zone functions (`MakeAKSLabelZoneFromVM`, `GetAKSLabelZoneFromAKSMachine`, etc.) to return `RegionalZone` instead of `""`
- Refactor `MakeAKSLabelZoneFromARMZone()` to no longer accept or return empty strings
- Remove all empty-string zone handling throughout the codebase

**How was this change tested?**

* Unit tests for zone utility functions (`pkg/utils/zone_test.go`)
* Unit tests for instance type provider zone-aware provisioning, including:
  - Regional instance types get zone label `"0"` in zonal regions
  - No empty zone domain in any instance type offering (regression guard)
  - Non-zonal SKUs excluded via zone NodePool requirements (single zone and all zones)
  - Topology spread constraints work correctly when non-zonal SKUs exist (reproduces #1384)
  - Provisioning in non-zonal regions still works
* Unit tests for AKS machine instance utils (`BuildNodeClaimFromAKSMachine`, `GetAKSLabelZoneFromAKSMachine`)
* Unit tests for cloud provider (`pkg/cloudprovider/`) including AKS machine API offerings
* Full test suites pass: `pkg/utils`, `pkg/providers/instance`, `pkg/providers/instancetype`, `pkg/cloudprovider`
* `make presubmit` passes

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: #
- [x] No

**Release Note**

```release-note
fix: Regional (non-zonal) VM SKUs now use zone value "0" instead of "" (empty string) for topology.kubernetes.io/zone, matching the label AKS places on non-zonal nodes. This fixes topology spread constraint deadlocks when non-zonal SKUs exist in a zonal region (issue #1384). Users can now filter out regional SKUs via NodePool requirements on topology.kubernetes.io/zone.
```

### CODE REVIEW

File: pkg/cloudprovider/suite_aksmachineapi_offerings_test.go [hunk 1]
```diff
@@ -343,7 +343,7 @@ var _ = Describe("CloudProvider", func() {
 				ExpectProvisionedAndWaitForPromises(ctx, env.Client, cluster, cloudProvider, coreProvisioner, azureEnv, pod)
 
 				node := ExpectScheduled(ctx, env.Client, pod)
-				Expect(node.Labels).To(HaveKeyWithValue(v1.LabelTopologyZone, ""))
+				Expect(node.Labels).To(HaveKeyWithValue(v1.LabelTopologyZone, utils.RegionalZone))
```
Comment (matthchr) [inline pkg/cloudprovider/suite_aksmachineapi_offerings_test.go]: minor, feel free to ignore: bare utils packages and `utils.Xyz` make me sad.

`utils/zone/...` and usage `zone.Regional` would read better.

File: pkg/utils/zone.go [hunk 2]
```diff
@@ -23,39 +23,53 @@ import (
...
-	}
-	if len(vm.Zones) == 1 {
-		if vm.Location == nil {
-			return "", fmt.Errorf("virtual machine is missing location")
-		}
-		return MakeAKSLabelZoneFromARMZone(*vm.Location, *(vm.Zones)[0]), nil
-	}
-	if len(vm.Zones) > 1 {
-		return "", fmt.Errorf("virtual machine has multiple zones")
+	location := ""
```
Comment (matthchr) [inline pkg/utils/zone.go]: minor: This is `lo.FromPtr` behavior, AFAIK.

**Review by matthchr — DISMISSED** [review]
LGTM, 2 small nits

File: pkg/cloudprovider/suite_aksmachineapi_offerings_test.go (hunk 1 above)
Comment (tallaxes) [reply pkg/cloudprovider/suite_aksmachineapi_offerings_test.go]: Done; used utils/zones/... (because zone as a variable is just too convenient, and `zones.Regional` still works, I think)

**Review by matthchr — DISMISSED** [review]

**Review by matthchr — APPROVED** [review]
