### PR TITLE
fix: mark spot as unavailable on LowPriorityQuota

### LINKED ISSUE #91: LowPriorityCoresQuota error should mark spot as unavailable
### Tell us about your request

Any roadmap to support scale spot node fail, and fallback to on-demand node? 

I saw Karpenter is AWS already easy to support.
https://github.com/aws/karpenter-provider-aws/blob/e00c97c3c834a1349a4126f69500fdcc4caf1344/website/content/en/v0.32/faq.md?plain=1#L82

but in Azure, if the spot instance cannot created succuess, that will crash, cannot failback to on-demand.

### Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?

to save the cost, balance the spot and on-demand resources.

### Are you currently working around this issue?

no

### Additional Context

image
Tested on Azure, I create a deployment with 4 gpu pod. And I only have 3 gpu spot quota.
As design, it will create the fourth node with on-demand, but now always crash in the fourth node in spot.

### Attachments

_No response_

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by Bryce-Soghigian**
Fixes #91 

**Description**
If spot capacity hits the spot regional cores count, karpenter should fall back onto on-demand. This PR adds that functionality

**How was this change tested?**
- make presubmt 
- Manual repro where i first reproed the issue presented in #91 , then proceeded to build a new image with this code and validate it will successfully choose on demand instances if spot capacity is fully used up. 

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note
feat: fail-over to on-demand if spot capacity is unavailable
```

### CODE REVIEW

**Review by Bryce-Soghigian — COMMENTED** [review]
/test

File: pkg/cache/unavailableofferings.go [hunk 1]
```diff
@@ -69,6 +69,15 @@ func (u *UnavailableOfferings) MarkUnavailable(ctx context.Context, unavailableR
...
 }
 
+func (u *UnavailableOfferings) Put(key string, value struct{}, ttl time.Duration) {
+	u.cache.Set(key, value, ttl)
+}
+
+func (u *UnavailableOfferings) Has(key string) bool {
+	_, found := u.cache.Get(key)
+	return found
+}
```
Comment (tallaxes) [inline pkg/cache/unavailableofferings.go:79]: This seems to expose too much of the implementaional detail of UnavailableOfferings - and no reason to pass value? How about adding a method like MarkSpotUnavailableWithTTL, instead of opening the cache for direct manipulation? It could also  maybe use synthetic key("","",spot), instead of the specific error string?

File: pkg/providers/instance/instance.go [hunk 2]
```diff
@@ -415,7 +415,14 @@ func (p *Provider) launchInstance(
 	return resp, instanceType, nil
 }
 
+// nolint:gocyclo
 func (p *Provider) handleResponseErrors(ctx context.Context, instanceType *corecloudprovider.InstanceType, zone, capacityType string, err error) error {
+	if sdkerrors.LowPriorityQuotaHasBeenReached(err) {
+		// Mark in cache that spot quota has been reached for this subscription
+		p.unavailableOfferings.Put(sdkerrors.LowPriorityQuotaExceededTerm, struct{}{}, SubscriptionQuotaReachedTTL)
```
Comment (tallaxes) [inline pkg/providers/instance/instance.go:422]: See elsewhere on Put. I also slightly dislike the use of the error term as key, but this is less important (and best decided within unavailableOffereings implementation)

File: pkg/providers/instance/instance.go [hunk 3]
```diff
@@ -415,7 +415,14 @@ func (p *Provider) launchInstance(
...
+		logging.FromContext(ctx).Error(err)
+		return fmt.Errorf("LowPriorityQuota Has been reached and this subscription has hit the regional vCPU quota for spot. To scale beyond this limit, please review the quota increase process here: https://docs.microsoft.com/en-us/azure/azure-portal/supportability/low-priority-quota")
```
Comment (tallaxes) [inline pkg/providers/instance/instance.go:424]:
```suggestion
		return fmt.Errorf("this subscription has reached the regional vCPU quota for spot (LowPriorityQuota). To scale beyond this limit, please review the quota increase process here: https://docs.microsoft.com/en-us/azure/azure-portal/supportability/low-priority-quota")
```

File: pkg/providers/instancetype/instancetypes.go [hunk 4]
```diff
@@ -136,7 +136,7 @@ func (p *Provider) createOfferings(sku *skewer.SKU, zones sets.Set[string]) []cl
 		onDemandPrice, onDemandOk := p.pricingProvider.OnDemandPrice(*sku.Name)
 		spotPrice, spotOk := p.pricingProvider.SpotPrice(*sku.Name)
 		availableOnDemand := onDemandOk && !p.unavailableOfferings.IsUnavailable(*sku.Name, zone, corev1beta1.CapacityTypeOnDemand)
-		availableSpot := spotOk && !p.unavailableOfferings.IsUnavailable(*sku.Name, zone, corev1beta1.CapacityTypeSpot)
+		availableSpot := spotOk && !p.unavailableOfferings.IsUnavailable(*sku.Name, zone, corev1beta1.CapacityTypeSpot) && !p.unavailableOfferings.Has(sdkerrors.LowPriorityQuotaExceededTerm)
```
Comment (tallaxes) [inline pkg/providers/instancetype/instancetypes.go:139]: Can the new check be added within IsUnavailable? Simpler and easier to use, better encapsulation / don't need Has ...

File: pkg/providers/instancetype/suite_test.go [hunk 5]
```diff
@@ -172,6 +172,42 @@ var _ = Describe("InstanceType Provider", func() {
...
+						Body: createSDKErrorBody(sdkerrors.OperationNotAllowed, LowPriorityCoresQuotaErrorMessage),
+					},
+				},
+			)
+			// Create a pod that should fail to schedule
+			pod := coretest.UnschedulablePod()
+			ExpectProvisioned(ctx, env.Client, cluster, cloudProvider, coreProvisioner, pod)
+			ExpectNotScheduled(ctx, env.Client, pod)
+			azureEnv.VirtualMachinesAPI.VirtualMachineCreateOrUpdateBehavior.BeginError.Set(nil)
+			pod = coretest.UnschedulablePod()
```
Comment (tallaxes) [inline pkg/providers/instancetype/suite_test.go:198]: Yikes. This clearly shows the limitations of current support for faking errors. We need something along the lines of [EC2Behavior.InsufficientCapacityPools](https://github.com/search?q=repo%3Aaws%2Fkarpenter-provider-aws%20InsufficientCapacityPools&type=code) ...

In any case, likely don't need a new unschedulable pod?

**Review by tallaxes — CHANGES_REQUESTED** [review]
Like the direction, left some comments. 

May also want to rename this to something like "fix: mark spot as unavailable on LowPriorityQuota" (what actually happens after depends on other configuration)

File: pkg/cache/unavailableofferings.go (hunk 1 above)
Comment (Bryce-Soghigian) [reply pkg/cache/unavailableofferings.go:79]: synthetic key makes a lot of sense, will switch to that

File: pkg/providers/instance/instance.go (hunk 2 above)
Comment (Bryce-Soghigian) [reply pkg/providers/instance/instance.go]: Agree removed

File: pkg/providers/instancetype/instancetypes.go (hunk 4 above)
Comment (Bryce-Soghigian) [reply pkg/providers/instancetype/instancetypes.go]: yep

File: pkg/providers/instancetype/suite_test.go (hunk 5 above)
Comment (Bryce-Soghigian) [reply pkg/providers/instancetype/suite_test.go]: removed the second pod

File: pkg/cache/unavailableofferings.go (hunk 1 above)
Comment (tallaxes) [reply pkg/cache/unavailableofferings.go]: The new changes go in the right direction I think, but I would suggest taking the next step and 

* Implement MarkSpotUnavailableWithTTL method on UnavailableOfferings (that would use the synthetic key internally) - this would remove from the consume the need to know anything about implementation; and 
* Add the check for this key into the already existing IsUnavailable (would check for this first, if asked about spot), which the consumer would call as before, without special casing / knowing anything about extra check for spot behind the scenes.

File: pkg/providers/instancetype/instancetypes.go (hunk 4 above)
Comment (tallaxes) [reply pkg/providers/instancetype/instancetypes.go]: Sorry I did not make myself clear; I meant adding th check within IsUnavailable _implementation_ - so this call would not even need to change.

File: pkg/cache/unavailableofferings.go (hunk 1 above)
Comment (Bryce-Soghigian) [reply pkg/cache/unavailableofferings.go]: gotcha that makes sense

**Comment by Bryce-Soghigian** [comment]
implemented all that was mentioned

File: pkg/cache/unavailableofferings.go [hunk 6]
```diff
@@ -48,10 +49,18 @@ func NewUnavailableOfferings() *UnavailableOfferings {
 
 // IsUnavailable returns true if the offering appears in the cache
 func (u *UnavailableOfferings) IsUnavailable(instanceType, zone, capacityType string) bool {
+	if _, ok := u.cache.Get(u.key("", "", v1beta1.CapacityTypeSpot)); ok && capacityType == v1beta1.CapacityTypeSpot {
```
Comment (tallaxes) [inline pkg/cache/unavailableofferings.go:52]: Checking capacityType first would be faster. Can also pre-compute the key, once. (To minimize performance impact we introduce here. Yes, slight, but called frequently ..) Otherwise 👍

Comment (Bryce-Soghigian) [reply pkg/cache/unavailableofferings.go:52]: Is there a way to write 

``` 
if capacityType == v1beta1.CapacityTypeSpot {
		if _, ok := u.cache.Get(SpotUnavailableKey); ok {
			return true
		}
	}
``` 
As 
```
if capacityType == v1beta1.CapacityTypeSpot && _, ok := u.cache.Get(SpotUnavailableKey); ok {
```


```
The Go programming language does not allow declarations
 after &&. This is because && is a logical operator
 that returns true if both of its operands are true, and false otherwise. If a declaration were allowed after &&, it would be possible for the declaration to be executed before the && operator is evaluated, which could lead to sadness
For example, consider the following code
if true && var := 1; var > 0 {
  // This code will be executed, even if var is not initialized.
}

In this example, the variable var is declared after the && operator. This means that the declaration will be executed before the && operator is evaluated. If var is not initialized before the && operator is evaluated, it will be equal to the zero value of its type, which is 0. This means that the && operator will evaluate to false, and the code inside the if statement will not be executed.
To avoid this problem, declarations must be made before the && operator. This ensures that the declaration is executed before the && operator is evaluated, and that the variable is initialized before it is used.
```


I wanted to write the cpaaciyy type check before, but encountered this problem. I can use the first syntax to accomplish this just wondering if there is a better way i am missing.

Comment (tallaxes) [reply pkg/cache/unavailableofferings.go]: Not that I know of; I would not worry about it

File: pkg/cache/unavailableofferings.go [hunk 7]
```diff
@@ -31,27 +32,43 @@ import (
...
+	spotKey string
 }
 
 func NewUnavailableOfferingsWithCache(c *cache.Cache) *UnavailableOfferings {
-	return &UnavailableOfferings{
-		cache: c,
+	u := &UnavailableOfferings{
+		cache: cache.New(UnavailableOfferingsTTL, DefaultCleanupInterval),
 	}
+	u.spotKey = u.key("", "", v1beta1.CapacityTypeSpot)
```
Comment (tallaxes) [inline pkg/cache/unavailableofferings.go:44]: If you change `key()` to non-member (which should not be a problem), all this unpleasantness would go away

File: pkg/cache/unavailableofferings.go (hunk 6 above)
Comment (Bryce-Soghigian) [reply pkg/cache/unavailableofferings.go]: sg

**Review by tallaxes — APPROVED** [review]
LGTM👍

**Review by tallaxes — APPROVED** [review]
