### PR TITLE
fix: Attach Managed NSG to NIC when in BYO VNET mode

### LINKED ISSUE #562: Load balancing doesn't work correctly in BYO VNET scenarios
### Version

__Karpenter Version:__ v0.7.0

__Kubernetes Version:__ v1.3.0

If you use BYO VNET for your AKS cluster with Standard Public LB, the ingress traffic only hits the nodes of the system nodepool and not the karpenter nodes. In this scenario AKS automatically creates a NSG and attaches it to the network interfaces of the system nodes and not to the karpenter nodes. This behavior ultimately blocks the ingress traffic to reach karpenter nodes. If the externalTrafficPolicy is set to Cluster, the traffic can reach the nodes through an extra hop from the system nodes but never directly. However if you set the externalTrafficPolicy to Local, there is no way to forward ingress traffic to the karpenter nodes. 

### Expected Behavior

An NSG should be associated with the karpenter nodes also, not just with the system nodes to enable ingress traffic from the public LB. 

### Actual Behavior

See above, due to the missing NSG, traffic can't reach the karpenter nodes directly. 

### Steps to Reproduce the Problem

Create a cluster with karpenter.
Install NGINX ingress controller with externalTrafficPolicy set to local. 
Force the NGINX pods to move to the karpenter nodes. 
Create an ingress and a backend app. 
Try to reach the public LB externally. 

### Resource Specs and Logs

-

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by matthchr**
This mirrors what AKS does. This is not required in managed VNET mode because then the NSG is attached to the Subnet (created by AKS), so it doesn't need to be attached to each NIC individually.

Fixes #562.
This supersedes #610, which should be closed.

**How was this change tested?**

* Unit tests
* E2E tests (see newly added test). Full E2E run results: https://github.com/Azure/karpenter-provider-azure/actions/runs/15312805268
* Manually tested the scenario reported in #562 using `make az-all-custom-vnet`

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note
Fix bug which caused load balancing to not work correctly in BYO VNET scenarios.
```

### CODE REVIEW

File: pkg/providers/instance/instance.go [hunk 1]
```diff
@@ -306,6 +306,14 @@ func (p *DefaultProvider) newNetworkInterfaceForVM(opts *createNICOptions) armne
 	if err := opts.InstanceType.Requirements.Compatible(skuAcceleratedNetworkingRequirements); err == nil {
 		enableAcceleratedNetworking = true
 	}
+
+	var nsgRef *armnetwork.SecurityGroup
```
Comment (matthchr) [inline pkg/providers/instance/instance.go:310]: Note to self that I need to run manual test one more time to ensure the full LB scenario works E2E now.
