### PR TITLE
fix: set `DisableKubeletCloudCredentialProviders=false` for versions without OOT credential provider (1.29)

### LINKED ISSUE #411: Nodes created by Karpenter are unable to pull images from a private Azure Container Registry (ACR), resulting in a 401 Unauthorized error
### Version

__Karpenter Version:__ v0.5.0

__Kubernetes Version:__ v1.29.4

### Expected Behavior

The expected behavior is that the nodes can access the private ACR using the configured managed identity.

### Actual Behavior

Nodes created by Karpenter and regular Kubernetes nodes both have the same managed identity configured. This managed identity has been granted both AcrPull and AcrPush roles on the ACR. However, while pods on regular Kubernetes nodes can successfully pull images from the private ACR, pods on nodes created by Karpenter fail with the following error: 401 Unauthorized
Screenshot 2024-06-19 at 12 57 59

### Steps to Reproduce the Problem

az aks update -n aks-dev -g rg-dev --attach-acr myregistry

### Resource Specs and Logs

>   Events:
>   Type     Reason                  Age                    From               Message
>   ----     ------                  ----                   ----               -------
>   Warning  FailedScheduling        39m                    default-scheduler  0/1 nodes are available: 1 Insufficient cpu. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
>   Normal   Scheduled               37m                    default-scheduler  Successfully assigned default/test-779d54dfd-djk7d to aks-general-purpose-zfxqd
>   Normal   Nominated               39m                    karpenter          Pod should schedule on: nodeclaim/general-purpose-zfxqd
>   Warning  FailedCreatePodSandBox  37m                    kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "1d4cfc55733b95293627a57ffb7a20de269debdf1b2afc2116aeb103042afeb4": plugin type="cilium-cni" failed (add): failed to invoke delegated plugin ADD for IPAM: http request failed: Post "http://localhost:10090/network/requestipconfigs": dial tcp 127.0.0.1:10090: connect: connection refused; failed to request IP address from CNS
>   Normal   SandboxChanged          36m (x5 over 37m)      kubelet            Pod sandbox changed, it will be killed and re-created.
>   Normal   Pulling                 36m (x3 over 36m)      kubelet            Pulling image "myregistry.azurecr.io/test-image:latest"
>   Warning  Failed                  36m (x3 over 36m)      kubelet            Failed to pull image "myregistry.azurecr.io/test-image:latest": failed to pull and unpack image "myregistry.azurecr.io/test-image:latest": failed to resolve reference "myregistry.azurecr.io/test-image:latest": failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://myregistry.azurecr.io/oauth2/token?scope=repository%3Atest-image%3Apull&service=myregistry.azurecr.io: 401 Unauthorized
>   Warning  Failed                  36m (x3 over 36m)      kubelet            Error: ErrImagePull
>   Warning  Failed                  35m (x5 over 36m)      kubelet            Error: ImagePullBackOff
>   Normal   BackOff                 2m29s (x152 over 36m)  kubelet            Back-off pulling image "myregistry.azurecr.io/test-image:latest"

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by Bryce-Soghigian**
Fixes #411

**Description**
https://github.com/Azure/karpenter-provider-azure/blob/main/pkg/providers/imagefamily/bootstrap/aksbootstrap.go#L425
```
// CredentialProviderURL returns the URL for OOT credential provider,
// or an empty string if OOT provider is not to be used
func CredentialProviderURL(kubernetesVersion, arch string) string {
  minorVersion := semver.MustParse(kubernetesVersion).Minor
  if minorVersion < 30 { 
    return ""
  }
```

Looks like from this code for out of tree provider we default to not including the settings for out of tree provider if CredentialProviderURL is empty. 

DisableKubeletCloudCredentialProviders | false | Alpha | 1.23 | 1.28
-- | -- | -- | -- | --
DisableKubeletCloudCredentialProviders | true | Beta | 1.29 | –

We don't have the logic conditionally enabled for 1.29, so auth pull will not work for that specific kubernetes version. 

This can be easily fixed by 

A) Switching 1.29 to use out of tree credential provider.(Have karpenter pass in the rest of the required OOT Provider kubelet flags.)
B) Adding the default to false for the feature gate for 1.29 clusters. 

To have consistency with the provisioning of the AKS Resource Provider nodes, we will choose option B. 

**How was this change tested?**
- make az-all 
- make presubmit 
- az e2etest acr

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note
fixes acr pull on 1.29
```

### CODE REVIEW

**Comment by Bryce-Soghigian** [comment]
~/dev/focus/karpenter-provider-azure (bsoghigian/disable-credential-providers*) ¬ª k get nodes                                  sillygoose@Bryces-MacBook-Pro
NAME                                STATUS   ROLES    AGE   VERSION
aks-nodepool1-34775126-vmss000000   Ready    <none>   14h   v1.29.0
aks-nodepool1-34775126-vmss000001   Ready    <none>   14h   v1.29.0
aks-nodepool1-34775126-vmss000002   Ready    <none>   14h   v1.29.0
---
< Exit [AfterEach] TOP-LEVEL - /Users/sillygoose/dev/focus/karpenter-provider-azure/test/suites/acr/suite_test.go:43 @ 08/14/24 09:35:22.275 (41ms)
‚Ä¢ [357.830 seconds]
------------------------------

Ran 1 of 1 Specs in 358.025 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
--- PASS: TestAcr (358.03s)
PASS
ok      github.com/Azure/karpenter-provider-azure/test/suites/acr       358.562s
kubectl taint nodes CriticalAddonsOnly=true:NoSchedule- --all
node/aks-nodepool1-34775126-vmss000000 untainted
node/aks-nodepool1-34775126-vmss000001 untainted
node/aks-nodepool1-34775126-vmss000002 untainted
-
----

Here is the proof of karpenter e2e successfully passing for these scenarios on a 1.29 cluster. One thing to check is just double check that az-import doesnt also inherit other traits of the image(possibly importing the pause container image for the acr image pull test may also inherit unauthorized pulls or something?)

File: pkg/providers/imagefamily/bootstrap/aksbootstrap.go [hunk 1]
```diff
@@ -437,6 +437,9 @@ func CredentialProviderURL(kubernetesVersion, arch string) string {
 		credentialProviderVersion = "1.29.2"
 	case 30:
 		credentialProviderVersion = "1.30.0"
+
+	case 31:
+		credentialProviderVersion = "1.31.0"
```
Comment (tallaxes) [inline pkg/providers/imagefamily/bootstrap/aksbootstrap.go:442]: I presume you checked there is one (for both amd and arm), and it will be supported?

**Review by tallaxes — APPROVED** [review]
